default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["POSTGRES_DB"] || "cidade_estado" %>
  username: <%= ENV["POSTGRES_USER"] || "root" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "root1234" %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
